services:
  charliecore-sentinel:
    container_name: charliecore-sentinel
    image: marksanti/charliecore:latest
    restart: unless-stopped
    env_file:
      - config/keys.env
    volumes:
      - ./logs:/app/logs
      - ./indicators:/app/indicators
    working_dir: /app
    command: python sentinel.py
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - TZ=America/Sao_Paulo
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--interval 86400 --cleanup --notification-url=discord://PXpwl6uE7XfXUbZtxhlhpg9EDi9pzY4R5_JH2_DqVLZjds41aWlKxb4C8tOwWIHtzFTj@1396935848498430002"
    labels:
      com.centurylinklabs.watchtower.enable: "false"
